# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.3, generator: @autorest/python@6.1.6)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class DeviceCreateInputBillingCycle(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The billing cycle of the device."""

    HOURLY = "hourly"
    DAILY = "daily"
    MONTHLY = "monthly"
    YEARLY = "yearly"


class DeviceCreateInputIpAddressesInnerAddressFamily(
    int, Enum, metaclass=CaseInsensitiveEnumMeta
):
    """Address Family for IP Address."""

    FOUR = 4
    SIX = 6


class DeviceState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DeviceState."""

    ACTIVE = "active"
    DELETED = "deleted"
    DEPROVISIONING = "deprovisioning"
    FAILED = "failed"
    INACTIVE = "inactive"
    QUEUED = "queued"
    REINSTALLING = "reinstalling"
    POST_PROVISIONING = "post_provisioning"
    POWERING_ON = "powering_on"
    POWERING_OFF = "powering_off"
    PROVISIONING = "provisioning"


class Enum13(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum13."""

    TWENTY = "20"
    TWENTY_ONE = "21"
    TWENTY_TWO = "22"
    TWENTY_THREE = "23"
    TWENTY_FOUR = "24"
    TWENTY_FIVE = "25"
    TWENTY_SIX = "26"
    TWENTY_SEVEN = "27"
    TWENTY_EIGHT = "28"
    TWENTY_NINE = "29"
    THIRTY = "30"
    THIRTY_ONE = "31"
    THIRTY_TWO = "32"
    THIRTY_THREE = "33"
    THIRTY_FOUR = "34"
    THIRTY_FIVE = "35"
    THIRTY_SIX = "36"
    THIRTY_SEVEN = "37"
    THIRTY_EIGHT = "38"
    THIRTY_NINE = "39"
    FORTY = "40"
    FORTY_ONE = "41"
    FORTY_TWO = "42"
    FORTY_THREE = "43"
    FORTY_FOUR = "44"
    FORTY_FIVE = "45"
    FORTY_SIX = "46"
    FORTY_SEVEN = "47"
    FORTY_EIGHT = "48"
    FORTY_NINE = "49"
    FIFTY = "50"
    FIFTY_ONE = "51"
    FIFTY_TWO = "52"
    FIFTY_THREE = "53"
    FIFTY_FOUR = "54"
    FIFTY_FIVE = "55"
    FIFTY_SIX = "56"
    FIFTY_SEVEN = "57"
    FIFTY_EIGHT = "58"
    FIFTY_NINE = "59"
    SIXTY = "60"
    SIXTY_ONE = "61"
    SIXTY_TWO = "62"
    SIXTY_THREE = "63"
    SIXTY_FOUR = "64"
    SIXTY_FIVE = "65"
    SIXTY_SIX = "66"
    SIXTY_SEVEN = "67"
    SIXTY_EIGHT = "68"
    SIXTY_NINE = "69"
    SEVENTY = "70"
    SEVENTY_ONE = "71"
    SEVENTY_TWO = "72"
    SEVENTY_THREE = "73"
    SEVENTY_FOUR = "74"
    SEVENTY_FIVE = "75"
    SEVENTY_SIX = "76"
    SEVENTY_SEVEN = "77"
    SEVENTY_EIGHT = "78"
    SEVENTY_NINE = "79"
    EIGHTY = "80"
    EIGHTY_ONE = "81"
    EIGHTY_TWO = "82"
    EIGHTY_THREE = "83"
    EIGHTY_FOUR = "84"
    EIGHTY_FIVE = "85"
    EIGHTY_SIX = "86"
    EIGHTY_SEVEN = "87"
    EIGHTY_EIGHT = "88"
    EIGHTY_NINE = "89"
    NINETY = "90"
    NINETY_ONE = "91"
    NINETY_TWO = "92"
    NINETY_THREE = "93"
    NINETY_FOUR = "94"
    NINETY_FIVE = "95"
    NINETY_SIX = "96"
    NINETY_SEVEN = "97"
    NINETY_EIGHT = "98"
    NINETY_NINE = "99"
    ONE_HUNDRED = "100"
    ONE_HUNDRED_ONE = "101"
    ONE_HUNDRED_TWO = "102"
    ONE_HUNDRED_THREE = "103"
    ONE_HUNDRED_FOUR = "104"
    ONE_HUNDRED_FIVE = "105"
    ONE_HUNDRED_SIX = "106"
    ONE_HUNDRED_SEVEN = "107"
    ONE_HUNDRED_EIGHT = "108"
    ONE_HUNDRED_NINE = "109"
    ONE_HUNDRED_TEN = "110"
    ONE_HUNDRED_ELEVEN = "111"
    ONE_HUNDRED_TWELVE = "112"
    ONE_HUNDRED_THIRTEEN = "113"
    ONE_HUNDRED_FOURTEEN = "114"
    ONE_HUNDRED_FIFTEEN = "115"
    ONE_HUNDRED_SIXTEEN = "116"
    ONE_HUNDRED_SEVENTEEN = "117"
    ONE_HUNDRED_EIGHTEEN = "118"
    ONE_HUNDRED_NINETEEN = "119"
    ONE_HUNDRED_TWENTY = "120"
    ONE_HUNDRED_TWENTY_ONE = "121"
    ONE_HUNDRED_TWENTY_TWO = "122"
    ONE_HUNDRED_TWENTY_THREE = "123"
    ONE_HUNDRED_TWENTY_FOUR = "124"
    ONE_HUNDRED_TWENTY_FIVE = "125"
    ONE_HUNDRED_TWENTY_SIX = "126"
    ONE_HUNDRED_TWENTY_SEVEN = "127"
    ONE_HUNDRED_TWENTY_EIGHT = "128"


class Enum14(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum14."""

    INCLUDE = "include"
    EXCLUDE = "exclude"
    ONLY = "only"


class Enum15(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum15."""

    INCLUDE = "include"
    EXCLUDE = "exclude"
    ONLY = "only"


class Enum18(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum18."""

    GLOBAL_IPV4 = "global_ipv4"
    PRIVATE_IPV4 = "private_ipv4"
    PUBLIC_IPV4 = "public_ipv4"
    PUBLIC_IPV6 = "public_ipv6"
    VRF = "vrf"


class FacilityFeaturesItem(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """FacilityFeaturesItem."""

    BAREMETAL = "baremetal"
    BACKEND_TRANSFER = "backend_transfer"
    LAYER2 = "layer_2"
    GLOBAL_IPV4 = "global_ipv4"
    IBX = "ibx"


class IPReservationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """IPReservationType."""

    GLOBAL_IPV4 = "global_ipv4"
    PUBLIC_IPV4 = "public_ipv4"
    PRIVATE_IPV4 = "private_ipv4"
    PUBLIC_IPV6 = "public_ipv6"


class MetalGatewayLiteState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The current state of the Metal Gateway. 'Ready' indicates the gateway record has been
    configured, but is currently not active on the network. 'Active' indicates the gateway has been
    configured on the network. 'Deleting' is a temporary state used to indicate that the gateway is
    in the process of being un-configured from the network, after which the gateway record will be
    deleted.
    """

    READY = "ready"
    ACTIVE = "active"
    DELETING = "deleting"


class PlanDeploymentTypesItem(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PlanDeploymentTypesItem."""

    ON_DEMAND = "on_demand"
    SPOT_MARKET = "spot_market"


class PlanLine(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PlanLine."""

    BAREMETAL = "baremetal"


class PlanSpecsDrivesInnerCategory(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PlanSpecsDrivesInnerCategory."""

    BOOT = "boot"
    CACHE = "cache"
    STORAGE = "storage"


class PlanSpecsDrivesInnerType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PlanSpecsDrivesInnerType."""

    HDD = "HDD"
    SSD = "SSD"
    NVME = "NVME"


class PlanSpecsNicsInnerType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PlanSpecsNicsInnerType."""

    ONE_GBPS = "1Gbps"
    TEN_GBPS = "10Gbps"
    TWENTY_FIVE_GBPS = "25Gbps"


class PlanType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The plan type."""

    STANDARD = "standard"
    WORKLOAD_OPTIMIZED = "workload_optimized"
    CUSTOM = "custom"


class PortNetworkType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Composite network type of the bond."""

    LAYER2_BONDED = "layer2-bonded"
    LAYER2_INDIVIDUAL = "layer2-individual"
    LAYER3 = "layer3"
    HYBRID = "hybrid"
    HYBRID_BONDED = "hybrid-bonded"


class PortType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type is either "NetworkBondPort" for bond ports or "NetworkPort" for bondable ethernet ports."""

    NETWORK_PORT = "NetworkPort"
    NETWORK_BOND_PORT = "NetworkBondPort"


class VrfIpReservationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """VrfIpReservationType."""

    VRF = "vrf"
